name: PoaSk
authors: [Ekpoa]
website: https://github.com/Ekpoa/PoaSkRewritev2
version: '4.12.1'
main: poa.poaskrewritev2.PoaSkRewritev2
api-version: '1.20'
depend:
    - Skript
commands:
  poasktest:
    permission: poa.poasktest
