name: PoaSk
authors: [Ekpoa]
website: https://github.com/Ekpoa/PoaSkRewritev2
version: '4.16.5'
main: poa.poaskrewritev2.PoaSkRewritev2
api-version: '1.20'
depend:
    - Skript

softdepend:
    - TAB
commands:
  poasktest:
    permission: poa.poasktest
