name: PoaSkRewritev2
authors: [Ekpoa]
website: https://github.com/Ekpoa/PoaSkRewritev2
version: '4.10.7'
main: poa.poaskrewritev2.PoaSkRewritev2
api-version: '1.20'
commands:
  poasktest:
    permission: poa.poasktest
